- package.json
- yarn.lock
Pr paquet eslint: https://github.com/padoa/npm-packages/pull/2325
> [Tech](RC) Fix eslint

- CODEOWNERS
https://docs.github.com/fr/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
> [Tech](RC) Add code owners

- package.json
- src/topics/engine/fixtures/box.builder.ts
- src/topics/engine/fixtures/box.mother.ts
- src/topics/engine/fixtures/fds-tree.builder.ts
- src/topics/engine/fixtures/fds-tree.mother.ts
- src/topics/engine/fixtures/fixtures.constants.ts
- src/topics/engine/fixtures/line.builder.ts
- src/topics/engine/fixtures/line.mother.ts
- src/topics/engine/fixtures/section.builder.ts
- src/topics/engine/fixtures/section.mother.ts
- src/topics/engine/fixtures/sub-section.builder.ts
- src/topics/engine/fixtures/sub-section.mother.ts
- src/topics/engine/fixtures/text.builder.ts
- src/topics/engine/fixtures/text.mother.ts
- src/topics/engine/model/fds.model.ts
- src/topics/engine/pdf-parser/tests/pdf-parser.service.test.ts
- src/topics/engine/transformer/tests/fds-tree-builder.service.test.ts
- yarn.lock
Ajout du pattern Mother/builder pour simplifier nos tests et les rendre plus maintenables.
> [TECH](RC) Add mother builder pattern

- src/__fixtures__/fixtures.constants.ts
- src/topics/engine/fds-engine.controller.ts
- src/topics/engine/pdf-extractor/tests/pdf-image-text-extractor.service.test.ts
- src/topics/engine/pdf-parser/tests/__snapshots__/pdf-parser.service.test.ts.snap
- src/topics/engine/pdf-parser/tests/pdf-parser.service.test.ts
- src/topics/engine/transformer/tests/fds-tree-cleaner.service.test.ts
Ajout de tests unitaires manquants pour le pdfParserService
> [TECH](RC) Ajout des tests unitaires manquants pour 100% coverage sur pdfParserService

- src/topics/engine/fixtures/box.mother.ts
- src/topics/engine/fixtures/fds-tree.mother.ts
- src/topics/engine/fixtures/fixtures.constants.ts
- src/topics/engine/fixtures/line.mother.ts
- src/topics/engine/fixtures/text.mother.ts
- src/topics/engine/rules/extraction-rules.ts
- src/topics/engine/rules/tests/extraction-rules.test.ts
> [TECH](RC) Last unit tests batch

- src/topics/engine/model/fds.model.ts
- src/topics/engine/rules/extraction-rules.ts
- src/topics/engine/rules/tests/extraction-rules.test.ts
front : https://github.com/padoa/haw-doctor-web/pull/21573
> [FEAT](RC) afficher les résultats du moteur => bloc des informations extraites

- src/tasks/extract/from-all-fds.ts
- src/topics/engine/fixtures/fds-tree.mother.ts
- src/topics/engine/fixtures/fixtures.constants.ts
- src/topics/engine/fixtures/line.mother.ts
- src/topics/engine/fixtures/text.mother.ts
- src/topics/engine/model/fds.model.ts
- src/topics/engine/rules/extraction-rules.ts
- src/topics/engine/rules/tests/extraction-rules.test.ts
* dangers = hazards + precautions
> [TECH](RC) Renommer hazards en dangers 

- src/topics/engine/__tests__/__snapshots__/fds-engine.service.test.ts.snap
- src/topics/engine/rules/__tests__/extraction-rules.test.ts
- src/topics/engine/rules/extraction-rules.ts
- src/topics/engine/rules/rules.constants.ts
front : https://github.com/padoa/haw-doctor-web/pull/21625/files
> [FEAT](RC) gérer la sélection de la date de révision de la FDS

- src/topics/engine/model/fds.model.ts
- src/topics/engine/pdf-extractor/pdf-stroke-extractor.service.ts
- src/topics/engine/pdf-extractor/pdf-text-extractor.service.ts
- src/topics/engine/transformer/__tests__/fds-tree-builder.service.test.ts
* MS-CHEMICAL-RISK: 
* Front: 
* Package:
> [Tech](RC) Fix review comment from add strokes pr

- package.json
```
npm run test-update path/to/my-file.ts
```
> [Feat](RC) Ajoute une commande pour mettre à jour les snapshots

- src/topics/engine/__tests__/__snapshots__/fds-engine.service.test.ts.snap
- src/topics/engine/model/fds.model.ts
- src/topics/engine/rules/__tests__/extraction-rules.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/revision-date-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/substances-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/revision-date-rules.service.ts
- src/topics/engine/rules/extraction-rules/substances-rules.service.ts
https://www.notion.so/padoa/Moteur-de-FDS-D-mo-front-afficher-les-r-sultats-du-moteur-g-rer-la-s-lection-des-substances-19ba7d20dbdb4c12b93f3c40d4cbdb0e?pvs=4
* MS-CHEMICAL-RISK: 
* Front:  https://github.com/padoa/haw-doctor-web/pull/21662
* Package:
> [FEAT](RC) gérer la sélection des substances 

- src/tasks/extract/from-all-fds.ts
Correction de l'output du extract all
> [TECH](RC) Fix extract all output

- src/tasks/extract/from-all-fds.ts
- src/topics/engine/__fixtures__/fds-tree.mother.ts
- src/topics/engine/__fixtures__/fixtures.constants.ts
- src/topics/engine/__fixtures__/line.mother.ts
- src/topics/engine/__fixtures__/text.mother.ts
- src/topics/engine/__tests__/__snapshots__/fds-engine.service.test.ts.snap
- src/topics/engine/model/fds.model.ts
- src/topics/engine/rules/__tests__/extraction-rules.test.ts
- src/topics/engine/rules/extraction-rules.service.ts
- src/topics/engine/rules/extraction-rules/__tests__/boiling-point-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/common-regex-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/boiling-point-rules.service.ts
- src/topics/engine/rules/extraction-rules/common-regex-rules.service.ts
- src/topics/engine/rules/extraction-rules/vapor-pressure.service.ts
Ajout de la règle pour récupérer le point d'ébullition dans le moteur de FDS
[Point d'ébullition](https://www.notion.so/padoa/Moteur-de-FDS-R-gle-bullition-Rajouter-une-r-gle-pour-extraire-les-informations-du-point-d-bulli-d032461323a5489ab92b61460ff9a32e)
> [TECH](RC) Add BoilingPoint rule

- src/tasks/extract/from-all-fds.ts
- src/topics/engine/rules/extraction-rules/__tests__/boiling-point-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/common-regex-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/boiling-point-rules.service.ts
- src/topics/engine/rules/extraction-rules/common-regex-rules.service.ts
- src/topics/engine/rules/extraction-rules/vapor-pressure.service.ts
Petites améliorations après avoir run le moteur FDS pour le point d'ébullition.
> [TECH](RC) improvements on BoilingPoint

- config/custom-environment-variables.json
- config/default.json
- config/local-local.json
- config/test.json
- src/routes.ts
- src/topics/pdftron/__test__/pdftron.test.ts
- src/topics/pdftron/pdftron.controller.ts
- src/topics/pdftron/pdftron.validator.ts
https://www.notion.so/padoa/Moteur-de-FDS-D-mo-front-afficher-les-r-sultats-du-moteur-route-pour-r-cup-rer-la-cl-PDFtron-2dc61d4fb909473da10c54ff3c872902?pvs=4
front : https://github.com/padoa/haw-doctor-web/pull/21730
> [TECH](RC) route pour récupérer la clé PDFtron  

- nyc.config.js
* MS-CHEMICAL-RISK: 
* Front: 
* Package:
> [Tech](RC) Coverage par des fichiers

- src/topics/engine/__tests__/__snapshots__/fds-engine.service.test.ts.snap
- src/topics/engine/model/fds.model.ts
- src/topics/engine/rules/__tests__/extraction-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/__fixtures__/cas-number.builder.ts
- src/topics/engine/rules/extraction-rules/__tests__/__fixtures__/cas-number.mother.ts
- src/topics/engine/rules/extraction-rules/__tests__/__fixtures__/ce-number.builder.ts
- src/topics/engine/rules/extraction-rules/__tests__/__fixtures__/ce-number.mother.ts
- src/topics/engine/rules/extraction-rules/__tests__/__fixtures__/concentration.builder.ts
- src/topics/engine/rules/extraction-rules/__tests__/__fixtures__/concentration.mother.ts
- src/topics/engine/rules/extraction-rules/__tests__/__fixtures__/substance.builder.ts
- src/topics/engine/rules/extraction-rules/__tests__/__fixtures__/substance.mother.ts
- src/topics/engine/rules/extraction-rules/__tests__/substance/cas-and-ce-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/substance/concentration-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/substances-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/substance/cas-and-ce-rules.service.ts
- src/topics/engine/rules/extraction-rules/substance/concentration-rules.service.ts
- src/topics/engine/rules/extraction-rules/substances-rules.service.ts
Ajoute les metadata dans chacun des champs des substances pour pouvoir mieux gérer les positions par la suite
ms-fds:https://github.com/padoa/ms-fds/pull/54
front: https://github.com/padoa/haw-doctor-web/pull/21743
> [Tech](RC) Ajoute les metadata dans chacun des champs des substances

- src/tasks/extract/from-all-fds.ts
- src/tasks/extract/from-fds.ts
* MS-CHEMICAL-RISK: 
* Front: 
* Package:
> [Tech](RC) Fix from-fds and from-all-fds

- src/topics/engine/__fixtures__/fixtures.constants.ts
- src/topics/engine/__fixtures__/text.mother.ts
- src/topics/engine/rules/__tests__/extraction-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/vapor-pressure.service.test.ts
- src/topics/engine/rules/extraction-rules/physical-state-rules.service.ts
- src/topics/engine/rules/extraction-rules/producer-rules.service.ts
- src/topics/engine/rules/extraction-rules/vapor-pressure.service.ts
Mise à jour de la règle de pression vapeur pour renvoyer le texte brut.
> [TECH](RC) Update vapor pressure rule to get raw text

- src/topics/engine/__fixtures__/fixtures.constants.ts
- src/topics/engine/__fixtures__/text.builder.ts
- src/topics/engine/__fixtures__/text.mother.ts
- src/topics/engine/__tests__/__snapshots__/fds-engine.service.test.ts.snap
- src/topics/engine/rules/__tests__/extraction-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/boiling-point-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/dangers-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/extraction-tools.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/vapor-pressure.service.test.ts
- src/topics/engine/rules/extraction-rules/boiling-point-rules.service.ts
- src/topics/engine/rules/extraction-rules/dangers-rules.service.ts
- src/topics/engine/rules/extraction-rules/extraction-rules.model.ts
- src/topics/engine/rules/extraction-rules/extraction-tools.service.ts
- src/topics/engine/rules/extraction-rules/vapor-pressure.service.ts
Motor rules (Dangers, boilingPoint) now return raw text
> [TECH](RC) Update motor to return rawtext for dangers and boiling point

- src/topics/engine/rules/extraction-rules/__tests__/extraction-tools.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/revision-date-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/boiling-point-rules.service.ts
- src/topics/engine/rules/extraction-rules/dangers-rules.service.ts
- src/topics/engine/rules/extraction-rules/extraction-rules.model.ts
- src/topics/engine/rules/extraction-rules/extraction-tools.service.ts
- src/topics/engine/rules/extraction-rules/revision-date-rules.service.ts
- src/topics/engine/rules/extraction-rules/vapor-pressure.service.ts
Return rawText when extracting date through GetRevisionDate
Enhanced helper to use capturingGroup
> [TECH](RC) Return rawText on DateByRevisionDate and enhance helper

- src/topics/engine/rules/extraction-rules/__tests__/revision-date-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/revision-date-rules.service.ts
- src/topics/engine/rules/extraction-rules/substance/substance-hazards-rules.service.ts
Update last dates extractor to return raw text
> [TECH](RC) V7: Update last dates extractor to return raw text

- src/topics/engine/rules/extraction-rules/__tests__/extraction-tools.service.test.ts
- src/topics/engine/rules/extraction-rules/boiling-point-rules.service.ts
- src/topics/engine/rules/extraction-rules/dangers-rules.service.ts
- src/topics/engine/rules/extraction-rules/dangers.regex.ts
- src/topics/engine/rules/extraction-rules/extraction-rules.model.ts
- src/topics/engine/rules/extraction-rules/extraction-tools.service.ts
- src/topics/engine/rules/extraction-rules/physical-state-rules.service.ts
- src/topics/engine/rules/extraction-rules/producer-rules.service.ts
- src/topics/engine/rules/extraction-rules/product-rules.service.ts
- src/topics/engine/rules/extraction-rules/substance/cas-and-ce-rules.service.ts
- src/topics/engine/rules/extraction-rules/substance/concentration-rules.service.ts
- src/topics/engine/rules/extraction-rules/substance/substance-hazards-rules.service.ts
- src/topics/engine/rules/extraction-rules/vapor-pressure.service.ts
Passage en rawtext pour les substances et refacto du code dupliqué.
> [TECH](RC) Rawtext on substances and refacto

- package.json
- src/tasks/extract/from-all-fds.ts
- src/topics/engine/__tests__/fds-engine.service.test.ts
- src/topics/engine/fds-engine.controller.ts
- src/topics/engine/fds-engine.service.ts
- src/topics/engine/fds-engine.validator.ts
- src/topics/engine/pdf-extractor/pdf-image-text-extractor.service.ts
- src/topics/engine/rules/extraction-rules/__tests__/substance/substance-hazards-rules.service.test.ts
- src/topics/pdftron/__test__/pdftron.test.ts
- src/topics/pdftron/pdftron.controller.ts
- yarn.lock
Ajoute un bouton pour valider la section.
C'est fait uniquement pour la section des fichiers. Il suffira par la suite de rappliquer la même logique aux autres blocs pour la suite.
https://www.notion.so/padoa/Moteur-de-FDS-Cr-ation-du-dataset-Cr-er-l-outillage-pour-pouvoir-annoter-manuellement-les-FDS-a7331f78d392410fa4c9f33689287eaf
* Ms-fds:  https://github.com/padoa/ms-fds/pull/69
* Front: https://github.com/padoa/haw-doctor-web/pull/21825
> [Tech](RC) Ajoute une route pour sauvegardé les données d'une section

- src/topics/engine/fds-engine.validator.ts
Sauvegarde la mention d'avertissement dans le JSON des données annotées
* ms-fds: https://github.com/padoa/ms-fds/pull/71
* Front: https://github.com/padoa/haw-doctor-web/pull/21972
> [Feat](RC) Ajoute la mention d'avertissement dans le JSON

- package.json
- src/topics/engine/__fixtures__/fds-tree.builder.ts
- src/topics/engine/__fixtures__/fds-tree.mother.ts
- src/topics/engine/__fixtures__/line.builder.ts
- src/topics/engine/__fixtures__/line.mother.ts
- src/topics/engine/__fixtures__/section.builder.ts
- src/topics/engine/__fixtures__/stroke.builder.ts
- src/topics/engine/__fixtures__/stroke.mother.ts
- src/topics/engine/__fixtures__/sub-section.builder.ts
- src/topics/engine/__fixtures__/sub-section.mother.ts
- src/topics/engine/pdf-extractor/__tests__/pdf-stroke-extractor.service.test.ts
- src/topics/engine/pdf-parser/__tests__/pdf-parser.service.test.ts
- src/topics/engine/rules/__tests__/extraction-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/boiling-point-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/dangers-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/extraction-tools.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/physical-state-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/producer-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/product-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/substance/cas-and-ce-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/substance/concentration-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/substance/substance-hazards-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/substance/table-extraction.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/substances-rules.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/vapor-pressure.service.test.ts
- src/topics/engine/rules/extraction-rules/__tests__/warning-notice.service.test.ts
- src/topics/engine/transformer/__tests__/fds-tree-builder.service.test.ts
- src/topics/engine/transformer/__tests__/fds-tree-cleaner.service.test.ts
- yarn.lock
Pr de refacto pour clean l'utilisation des properties avec les builders parce que ce n'est pas la bonne manière de faire
- ms-fds: https://github.com/padoa/ms-fds/pull/72
- Package: https://github.com/padoa/npm-packages/pull/2453
> [Tech](Rc) Replace properties by build
